default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: address_book_development

test:
  <<: *default
  database: address_book_test

production:
  <<: *default
  database: address_book_production